<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Store a new transaction generated by the frontend.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'tx_hash' => 'nullable|string',
            'wallet_address' => 'required|string',
            'receiver' => 'required|string',
            'amount' => 'required|numeric',
            'note' => 'nullable|string',
            'data_hash' => 'required|string',
        ]);

        $transaction = Transaction::create([
            'tx_hash' => $validated['tx_hash'] ?? null,
            'wallet_address' => $validated['wallet_address'],
            'receiver' => $validated['receiver'],
            'amount' => $validated['amount'],
            'note' => $validated['note'] ?? null,
            'data_hash' => $validated['data_hash'],
            'status' => 'confirmed' // Assuming creation happens after smart contract confirm
        ]);

        return response()->json([
            'status' => 'success',
            'message' => 'Transaction saved off-chain privately.',
            'data' => $transaction
        ], 201);
    }

    /**
     * Retrieve transactions for a specific sender or receiver wallet.
     */
    public function index(Request $request)
    {
        $wallet = $request->query('wallet');

        if (!$wallet) {
            return response()->json([
                'status' => 'error',
                'message' => 'Wallet address is required.'
            ], 400);
        }

        $transactions = Transaction::where('wallet_address', $wallet)
            ->orWhere('receiver', $wallet)
            ->orderBy('created_at', 'desc')
            ->get();

        return response()->json([
            'status' => 'success',
            'data' => $transactions
        ]);
    }

    /**
     * Look up a specific transaction using its block data hash.
     * This acts as the "bridge" between an on-chain record and the off-chain note.
     */
    public function show($hash)
    {
        $transaction = Transaction::where('data_hash', $hash)->first();

        if (!$transaction) {
            return response()->json([
                'status' => 'error',
                'message' => 'Transaction hash not found.'
            ], 404);
        }

        return response()->json([
            'status' => 'success',
            'data' => $transaction
        ]);
    }
}
