<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Store a new transaction generated by the frontend.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'tx_hash'        => 'nullable|string',
            'wallet_address' => 'required|string',
            'receiver'       => 'required|string',
            'amount'         => 'required|numeric',
            'note'           => 'nullable|string',
            'data_hash'      => 'required|string',
            'stealth_address' => 'nullable|string',
            'ephemeral_key'  => 'nullable|string',
        ]);

        $transaction = Transaction::create([
            'tx_hash'        => $validated['tx_hash'] ?? null,
            'wallet_address' => $validated['wallet_address'],
            'receiver'       => $validated['receiver'],       // Real receiver — encrypted at rest by AES-256
            'amount'         => $validated['amount'],         // Real amount — stored privately
            'note'           => $validated['note'] ?? null,   // Real note — encrypted at rest by AES-256
            'data_hash'      => $validated['data_hash'],
            'stealth_address' => $validated['stealth_address'] ?? null, // One-time on-chain address
            'ephemeral_key'  => $validated['ephemeral_key'] ?? null,    // Encrypted at rest by AES-256
            'status'         => 'confirmed'
        ]);

        return response()->json([
            'status' => 'success',
            'message' => 'Transaction saved off-chain privately.',
            'data' => $transaction
        ], 201);
    }

    /**
     * Retrieve transactions for a specific sender or receiver wallet.
     */
    public function index(Request $request)
    {
        $wallet = $request->query('wallet');

        if (!$wallet) {
            return response()->json([
                'status' => 'error',
                'message' => 'Wallet address is required.'
            ], 400);
        }

        $transactions = Transaction::where('wallet_address', $wallet)
            ->orWhere('receiver', $wallet)
            ->orderBy('created_at', 'desc')
            ->get();

        return response()->json([
            'status' => 'success',
            'data' => $transactions
        ]);
    }

    /**
     * Look up a specific transaction using its block data hash.
     * This acts as the "bridge" between an on-chain record and the off-chain note.
     */
    public function show($hash)
    {
        $transaction = Transaction::where('data_hash', $hash)->first();

        if (!$transaction) {
            return response()->json([
                'status' => 'error',
                'message' => 'Transaction hash not found.'
            ], 404);
        }

        return response()->json([
            'status' => 'success',
            'data' => $transaction
        ]);
    }
}
